add delivery slot to orders
LookBehind/nopCommerce pull request #74
Opened 2022-05-23 19:52 UTC by artashes-khalatyan

2022-05-29 19:00 UTC, LookBehind requested changes

2022-05-30 17:34 UTC, artashes-khalatyan commented on src/Presentation/Nop.Web/Areas/Admin/Factories/ProductModelFactory.cs
> +                    orderModel.Company = (await _companyService.GetCompanyByCustomerIdAsync(order.CustomerId)).Name;
we should create uniqueness deliveryslot+date+companyid so in our case we shouldnt have such kind of cases

2022-05-30 17:35 UTC, artashes-khalatyan commented on src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml
> +    <Value>DeliverySlot</Value>
done

2022-05-30 17:37 UTC, artashes-khalatyan commented on src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml
> +    <Value>Comapny</Value>
done

2022-05-30 17:38 UTC, artashes-khalatyan commented on src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml
> +    <Value>Comapny</Value>
done

2022-06-11 10:13 UTC, merged